version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5400:5432'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
