name: Deploy

on:
  push:
    tags:
      - 'v*'

env:
  CHART_NAME: novo-api
  STAGING_NS: novozymes-stage
  PROD_NS: novozymes
  NOVOZYMES_PULL_SECRET: ${{ secrets.NOVOZYMES_PULL_SECRET }}
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Latest Tag
        run: |
          git fetch --prune --unshallow --tags
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
      - name: Inject Private Keys
        run: |
          mkdir keys
          echo "${{ secrets.TIMESCALE_PEM }}" > keys/timescale.pem
          echo "${{ secrets.AWS_RDS_PEM }}" > keys/aws-rds.pem
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
          repository: ndustrialio/novo-api
          tag_with_ref: true
          tags: latest
          build_args: NPM_TOKEN=${{ secrets.NPM_TOKEN }}
      - name: Prepare helm chart
        run: |
          sed -i -e "s/appVersion:.*/appVersion: \\\"$LATEST_TAG\\\"/" ./charts/${CHART_NAME}/Chart.yaml
      - name: Setup Novozymes kubectl
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.NOVOZYMESKUBECONFIG }}
      - name: Deploy Novozymes Staging
        run: |
          echo $(helm version)
          helm upgrade ${CHART_NAME}-staging ./charts/${CHART_NAME}/ \
            --install --wait --atomic --namespace=${STAGING_NS} \
            -f ./charts/${CHART_NAME}/values-staging.yaml \
            --set image.tag=$LATEST_TAG \
            --set-string dockerPullSecret=$NOVOZYMES_PULL_SECRET
      - name: Test Novozymes Staging
        run: |
          helm test ${CHART_NAME}-staging --namespace=${STAGING_NS}
      - name: Deploy Novozymes Production
        run: |
          echo $(helm version)
          helm upgrade ${CHART_NAME} ./charts/${CHART_NAME}/ \
            --install --wait --atomic --namespace=${PROD_NS} \
            -f ./charts/${CHART_NAME}/values-prod.yaml \
            --set image.tag=$LATEST_TAG \
            --set-string dockerPullSecret=$NOVOZYMES_PULL_SECRET
      - name: Test Novozymes Production
        run: |
          helm test ${CHART_NAME} --namespace=${PROD_NS}